version: "3.8"
services:
  backend:
    build: 
      context: backend/.      
      network: host
    ports:
      - 5000:5000
  frontend:
    build:
      context: frontend/.
      network: host
    ports:
      - 3000:3000
